use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;

use crate::captions::TranscriptStream;
use crate::config::SourceKind;

pub async fn transcribe_with_command(
    media_path: &Path,
    work_dir: &Path,
    command: Option<&PathBuf>,
    args: &[String],
    timeout_seconds: Option<u64>,
) -> anyhow::Result<Option<TranscriptStream>> {
    let Some(command) = command.cloned().or_else(|| resolve_command("whisper")) else {
        return Ok(Some(TranscriptStream {
            source_kind: SourceKind::Asr,
            language: None,
            source_path: None,
            text: None,
            segments: Vec::new(),
            message: Some(
                "ASR skipped because no transcriber command was configured or found".to_string(),
            ),
        }));
    };
    tokio::fs::create_dir_all(work_dir).await?;
    let output_dir = work_dir.join("asr");
    tokio::fs::create_dir_all(&output_dir).await?;
    let output_path = whisper_json_path(media_path, &output_dir)?;
    if tokio::fs::try_exists(&output_path).await? {
        tokio::fs::remove_file(&output_path).await?;
    }

    run_whisper_command(
        &command,
        media_path,
        &output_dir,
        args,
        timeout_seconds,
    )
    .await?;

    let bytes = tokio::fs::read(&output_path).await.with_context(|| {
        format!(
            "transcriber succeeded but did not create expected Whisper JSON at {}",
            output_path.display()
        )
    })?;
    let mut parsed = text_transcripts::parse_whisper_json(&bytes)?;
    parsed.source = Some(output_path.to_string_lossy().into_owned());

    Ok(Some(TranscriptStream {
        source_kind: SourceKind::Asr,
        language: parsed.language.clone(),
        source_path: parsed.source.as_deref().map(PathBuf::from),
        text: parsed.text.clone(),
        segments: parsed.segments.into_iter().map(Into::into).collect(),
        message: Some(format!("ASR generated by {}", command.display())),
    }))
}

async fn run_whisper_command(
    command: &Path,
    media_path: &Path,
    output_dir: &Path,
    args: &[String],
    timeout_seconds: Option<u64>,
) -> anyhow::Result<()> {
    let mut process = tokio::process::Command::new(command);
    process
        .arg(media_path)
        .args(args)
        .arg("--output_dir")
        .arg(output_dir)
        .arg("--output_format")
        .arg("json")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true);

    let child = process
        .spawn()
        .with_context(|| format!("failed to start transcriber {}", command.display()))?;
    let output = if let Some(timeout_seconds) = timeout_seconds {
        tokio::time::timeout(Duration::from_secs(timeout_seconds), child.wait_with_output())
            .await
            .with_context(|| format!("transcriber timed out after {timeout_seconds} seconds"))??
    } else {
        child.wait_with_output().await?
    };

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!(
            "transcriber {} exited with {}: {}",
            command.display(),
            output.status,
            stderr.trim()
        );
    }
    Ok(())
}

fn whisper_json_path(media_path: &Path, output_dir: &Path) -> anyhow::Result<PathBuf> {
    let file_stem = media_path.file_stem().with_context(|| {
        format!(
            "cannot derive Whisper output name from media path {}",
            media_path.display()
        )
    })?;
    let mut output_path = output_dir.join(file_stem);
    output_path.set_extension("json");
    Ok(output_path)
}

fn resolve_command(command: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths)
            .map(|dir| dir.join(command))
            .find(|path| path.is_file())
    })
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::whisper_json_path;

    #[test]
    fn whisper_json_path_uses_media_file_stem() {
        let path = whisper_json_path(Path::new("/media/lecture.audio.wav"), Path::new("/work/asr"))
            .unwrap();
        assert_eq!(path, Path::new("/work/asr/lecture.audio.json"));
    }

    #[test]
    fn whisper_json_path_requires_a_file_name() {
        assert!(whisper_json_path(Path::new("/"), Path::new("/work/asr")).is_err());
    }
}
