use std::path::{Path, PathBuf};

use text_transcripts::Transcriber;

use crate::captions::TranscriptStream;
use crate::config::SourceKind;

pub async fn transcribe_with_command(
    media_path: &Path,
    work_dir: &Path,
    command: Option<&PathBuf>,
    args: &[String],
    timeout_seconds: Option<u64>,
) -> anyhow::Result<Option<TranscriptStream>> {
    let Some(command) = command.cloned().or_else(|| resolve_command("whisper")) else {
        return Ok(Some(TranscriptStream {
            source_kind: SourceKind::Asr,
            language: None,
            source_path: None,
            text: None,
            segments: Vec::new(),
            message: Some(
                "ASR skipped because no transcriber command was configured or found".to_string(),
            ),
        }));
    };
    tokio::fs::create_dir_all(work_dir).await?;
    let output_dir = work_dir.join("asr");
    tokio::fs::create_dir_all(&output_dir).await?;

    let media_path = media_path.to_path_buf();
    let args = args.to_vec();
    let command_for_message = command.clone();
    let parsed = tokio::task::spawn_blocking(move || {
        let mut transcriber = text_transcripts::WhisperCliTranscriber::from_options(
            text_transcripts::WhisperCliTranscriberOptions {
                command,
                args,
                output_dir: Some(output_dir),
                timeout_seconds,
            },
        );
        transcriber.transcribe(&media_path)
    })
    .await??;

    Ok(Some(TranscriptStream {
        source_kind: SourceKind::Asr,
        language: parsed.language.clone(),
        source_path: parsed.source.as_deref().map(PathBuf::from),
        text: parsed.text.clone(),
        segments: parsed.segments.into_iter().map(Into::into).collect(),
        message: Some(format!(
            "ASR generated by {}",
            command_for_message.display()
        )),
    }))
}

fn resolve_command(command: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths)
            .map(|dir| dir.join(command))
            .find(|path| path.is_file())
    })
}
