use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use tokio::process::Command;

use crate::captions::TranscriptStream;
use crate::config::SourceKind;

pub async fn transcribe_with_command(
    media_path: &Path,
    work_dir: &Path,
    command: Option<&PathBuf>,
    args: &[String],
    timeout_seconds: Option<u64>,
) -> anyhow::Result<Option<TranscriptStream>> {
    let Some(command) = command.cloned().or_else(|| resolve_command("whisper")) else {
        return Ok(Some(TranscriptStream {
            source_kind: SourceKind::Asr,
            language: None,
            source_path: None,
            text: None,
            segments: Vec::new(),
            message: Some(
                "ASR skipped because no transcriber command was configured or found".to_string(),
            ),
        }));
    };
    tokio::fs::create_dir_all(work_dir).await?;
    let output_dir = work_dir.join("asr");
    tokio::fs::create_dir_all(&output_dir).await?;
    let mut process = Command::new(&command);
    process
        .args(args)
        .arg(media_path)
        .arg("--output_format")
        .arg("json")
        .arg("--output_dir")
        .arg(&output_dir)
        .stdin(Stdio::null());
    let status = if let Some(seconds) = timeout_seconds {
        tokio::time::timeout(Duration::from_secs(seconds), process.status())
            .await
            .map_err(|_| {
                anyhow::anyhow!(
                    "transcriber command `{}` timed out after {seconds} seconds",
                    command.display()
                )
            })??
    } else {
        process.status().await?
    };
    if !status.success() {
        anyhow::bail!("transcriber command `{}` failed", command.display());
    }
    let transcript_path = find_json(&output_dir)
        .ok_or_else(|| anyhow::anyhow!("transcriber completed but no JSON transcript was found"))?;
    let bytes = tokio::fs::read(&transcript_path).await?;
    let parsed = text_transcripts::parse_whisper_json(&bytes)?;
    Ok(Some(TranscriptStream {
        source_kind: SourceKind::Asr,
        language: parsed.language.clone(),
        source_path: Some(transcript_path),
        text: parsed.text.clone(),
        segments: parsed
            .segments
            .into_iter()
            .map(text_transcripts::TranscriptSegmentContract::from)
            .collect(),
        message: Some(format!("ASR generated by {}", command.display())),
    }))
}

fn find_json(dir: &Path) -> Option<PathBuf> {
    let mut entries = std::fs::read_dir(dir)
        .ok()?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("json"))
        .collect::<Vec<_>>();
    entries.sort();
    entries.pop()
}

fn resolve_command(command: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths)
            .map(|dir| dir.join(command))
            .find(|path| path.is_file())
    })
}
